theme: jekyll-theme-slate
title: "Sionnach's Anki Decks"
description: "Sionnach's Collection of Anki Decks On Languages, Computing and More"
author: "Sionnach"
show_downloads: false
github:
   is_project_page: false
